version: '3.8'
services:
  node-test:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: node-project:latest
    container_name: node-test
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
