import { Cormorant_Garamond, Cinzel } from "next/font/google";
import "@styles/globals.css";
import Head from "next/head";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
});

const cinzel = Cinzel({ subsets: ["latin"], variable: "--font-cinzel" });

export const metadata = {
  title: "Iglesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* Developed by alexoh */}
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          http-equiv="Content-Security-Policy"
          content="default-src 'self'; script-src 'self'"
        />
      </Head>
      <html lang="en">
        <body className={`${cormorant.className} ${cinzel.variable} font-body bg-sanctuaryLinen text-sanctuaryDeep`}>
          {children}
        </body>
      </html>
    </>
  );
}
