import { Cormorant_Garamond, Cinzel } from "next/font/google";
import "@styles/globals.css";
import Head from "next/head";

const bodyFont = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
});

const displayFont = Cinzel({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-display",
});

export const metadata = {
  title: "Iglesia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* Developed by alexoh */}
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          http-equiv="Content-Security-Policy"
          content="default-src 'self'; script-src 'self'"
        />
      </Head>
      <html lang="en">
        <body
          className={`${bodyFont.variable} ${displayFont.variable} bg-sanctuary-cream font-body text-sanctuary-shadow antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
