import { Inter } from "next/font/google";
import "@styles/globals.css";
import "@fontsource/roboto";
import Head from "next/head";
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Iglesia",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = params;

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default; // Ajuste de ruta
  } catch (error) {
    notFound(); // Muestra 404 si no hay traducciones
  }

  return (
    <>
      <Head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          http-equiv="Content-Security-Policy"
          content="default-src 'self'; script-src 'self'"
        />
      </Head>
      <html lang={locale}>
        <body className={inter.className}>
          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </>
  );
}
